name: Prod

on:
  workflow_run:
    workflows: ["Dev"]
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Prod deployment"

    environment: 'Prod'
